[context.production.environment]
  REACT_APP_BASE_URL = "https://api.hackerlog.io/v1"

[context.deploy-preview.environment]
  REACT_APP_BASE_URL = "http://staging-api.hackerlog.io/v1"

[context.branch-deploy.environment]
  REACT_APP_BASE_URL = "http://staging-api.hackerlog.io/v1"

[context.develop.environment]
  REACT_APP_BASE_URL = "http://staging-api.hackerlog.io/v1"
