// flow-typed signature: 20b1b8816bc0fb7308934e208fd879fd
// flow-typed version: <<STUB>>/@types/jest_v^23.1.5/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
