// flow-typed signature: cdbbb863025c94e17b8d51aeb78aaa6a
// flow-typed version: <<STUB>>/@types/lodash-es_v^4.17.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/lodash-es'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/lodash-es' {
  declare module.exports: any;
}
