// flow-typed signature: 717638a0d92c9416e3b5518081b5c888
// flow-typed version: <<STUB>>/@types/node_v^10.5.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
