// flow-typed signature: 1170da4b0b5d58e1b129823d2f78e699
// flow-typed version: <<STUB>>/@types/react-loadable_v^5.4.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-loadable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-loadable' {
  declare module.exports: any;
}
