// flow-typed signature: bb88cb078d1742caf734f4b1433f115e
// flow-typed version: <<STUB>>/@types/react_v^16.4.6/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
