// flow-typed signature: a77258e9361aad772029773ad270207c
// flow-typed version: <<STUB>>/@types/react-modal_v^3.2.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-modal' {
  declare module.exports: any;
}
