// flow-typed signature: 768148559192390d9515f6ffebfeb8ae
// flow-typed version: <<STUB>>/cloudinary-react_v^1.0.6/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cloudinary-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cloudinary-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cloudinary-react/dist/cloudinary-react' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/components/CloudinaryComponent/CloudinaryComponent' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/components/CloudinaryContext/CloudinaryContext' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/components/Image/Image' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/components/Transformation/Transformation' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/components/Video/Video' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/index' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/Util/closestAbove' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/Util/debounce' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/Util/equals' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/Util/firstDefined' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/Util/isElement' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/Util/requestAnimationFrame' {
  declare module.exports: any;
}

declare module 'cloudinary-react/lib/Util/Util' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/components/CloudinaryComponent/CloudinaryComponent' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/components/CloudinaryContext/CloudinaryContext' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/components/Image/Image' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/components/Transformation/Transformation' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/components/Video/Video' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/index' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/Util/closestAbove' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/Util/debounce' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/Util/firstDefined' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/Util/isElement' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/Util/requestAnimationFrame' {
  declare module.exports: any;
}

declare module 'cloudinary-react/src/Util/Util' {
  declare module.exports: any;
}

declare module 'cloudinary-react/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cloudinary-react/dist/cloudinary-react.js' {
  declare module.exports: $Exports<'cloudinary-react/dist/cloudinary-react'>;
}
declare module 'cloudinary-react/lib/components/CloudinaryComponent/CloudinaryComponent.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/components/CloudinaryComponent/CloudinaryComponent'>;
}
declare module 'cloudinary-react/lib/components/CloudinaryContext/CloudinaryContext.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/components/CloudinaryContext/CloudinaryContext'>;
}
declare module 'cloudinary-react/lib/components/Image/Image.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/components/Image/Image'>;
}
declare module 'cloudinary-react/lib/components/Transformation/Transformation.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/components/Transformation/Transformation'>;
}
declare module 'cloudinary-react/lib/components/Video/Video.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/components/Video/Video'>;
}
declare module 'cloudinary-react/lib/index.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/index'>;
}
declare module 'cloudinary-react/lib/Util/closestAbove.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/Util/closestAbove'>;
}
declare module 'cloudinary-react/lib/Util/debounce.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/Util/debounce'>;
}
declare module 'cloudinary-react/lib/Util/equals.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/Util/equals'>;
}
declare module 'cloudinary-react/lib/Util/firstDefined.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/Util/firstDefined'>;
}
declare module 'cloudinary-react/lib/Util/isElement.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/Util/isElement'>;
}
declare module 'cloudinary-react/lib/Util/requestAnimationFrame.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/Util/requestAnimationFrame'>;
}
declare module 'cloudinary-react/lib/Util/Util.js' {
  declare module.exports: $Exports<'cloudinary-react/lib/Util/Util'>;
}
declare module 'cloudinary-react/src/components/CloudinaryComponent/CloudinaryComponent.js' {
  declare module.exports: $Exports<'cloudinary-react/src/components/CloudinaryComponent/CloudinaryComponent'>;
}
declare module 'cloudinary-react/src/components/CloudinaryContext/CloudinaryContext.js' {
  declare module.exports: $Exports<'cloudinary-react/src/components/CloudinaryContext/CloudinaryContext'>;
}
declare module 'cloudinary-react/src/components/Image/Image.js' {
  declare module.exports: $Exports<'cloudinary-react/src/components/Image/Image'>;
}
declare module 'cloudinary-react/src/components/Transformation/Transformation.js' {
  declare module.exports: $Exports<'cloudinary-react/src/components/Transformation/Transformation'>;
}
declare module 'cloudinary-react/src/components/Video/Video.js' {
  declare module.exports: $Exports<'cloudinary-react/src/components/Video/Video'>;
}
declare module 'cloudinary-react/src/index.js' {
  declare module.exports: $Exports<'cloudinary-react/src/index'>;
}
declare module 'cloudinary-react/src/Util/closestAbove.js' {
  declare module.exports: $Exports<'cloudinary-react/src/Util/closestAbove'>;
}
declare module 'cloudinary-react/src/Util/debounce.js' {
  declare module.exports: $Exports<'cloudinary-react/src/Util/debounce'>;
}
declare module 'cloudinary-react/src/Util/firstDefined.js' {
  declare module.exports: $Exports<'cloudinary-react/src/Util/firstDefined'>;
}
declare module 'cloudinary-react/src/Util/isElement.js' {
  declare module.exports: $Exports<'cloudinary-react/src/Util/isElement'>;
}
declare module 'cloudinary-react/src/Util/requestAnimationFrame.js' {
  declare module.exports: $Exports<'cloudinary-react/src/Util/requestAnimationFrame'>;
}
declare module 'cloudinary-react/src/Util/Util.js' {
  declare module.exports: $Exports<'cloudinary-react/src/Util/Util'>;
}
declare module 'cloudinary-react/webpack.config.js' {
  declare module.exports: $Exports<'cloudinary-react/webpack.config'>;
}
