// flow-typed signature: 5f68219aceb866227aa481b3117763fe
// flow-typed version: <<STUB>>/less-vars-to-js_v^1.2.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-vars-to-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-vars-to-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'less-vars-to-js/dist/index' {
  declare module.exports: any;
}

declare module 'less-vars-to-js/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'less-vars-to-js/dist/index.js' {
  declare module.exports: $Exports<'less-vars-to-js/dist/index'>;
}
declare module 'less-vars-to-js/test/index.js' {
  declare module.exports: $Exports<'less-vars-to-js/test/index'>;
}
