// flow-typed signature: 34f1a4535ad76f309a8a06882b6ba7f8
// flow-typed version: <<STUB>>/mst-react-router_v^2.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mst-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mst-react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mst-react-router/__test__/store.spec' {
  declare module.exports: any;
}

declare module 'mst-react-router/__test__/sync.spec' {
  declare module.exports: any;
}

declare module 'mst-react-router/dist/mst-react-router' {
  declare module.exports: any;
}

declare module 'mst-react-router/dist/mst-react-router.min' {
  declare module.exports: any;
}

declare module 'mst-react-router/src/store' {
  declare module.exports: any;
}

declare module 'mst-react-router/src/sync' {
  declare module.exports: any;
}

declare module 'mst-react-router/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mst-react-router/__test__/store.spec.js' {
  declare module.exports: $Exports<'mst-react-router/__test__/store.spec'>;
}
declare module 'mst-react-router/__test__/sync.spec.js' {
  declare module.exports: $Exports<'mst-react-router/__test__/sync.spec'>;
}
declare module 'mst-react-router/dist/mst-react-router.js' {
  declare module.exports: $Exports<'mst-react-router/dist/mst-react-router'>;
}
declare module 'mst-react-router/dist/mst-react-router.min.js' {
  declare module.exports: $Exports<'mst-react-router/dist/mst-react-router.min'>;
}
declare module 'mst-react-router/index' {
  declare module.exports: $Exports<'mst-react-router'>;
}
declare module 'mst-react-router/index.js' {
  declare module.exports: $Exports<'mst-react-router'>;
}
declare module 'mst-react-router/src/store.js' {
  declare module.exports: $Exports<'mst-react-router/src/store'>;
}
declare module 'mst-react-router/src/sync.js' {
  declare module.exports: $Exports<'mst-react-router/src/sync'>;
}
declare module 'mst-react-router/webpack.config.js' {
  declare module.exports: $Exports<'mst-react-router/webpack.config'>;
}
