// flow-typed signature: 53b857f053ee359e3128da0bf032b690
// flow-typed version: <<STUB>>/react-detect-offline_v^2.1.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-detect-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-detect-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-detect-offline/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-detect-offline/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-detect-offline/dist/index' {
  declare module.exports: any;
}

declare module 'react-detect-offline/src/index' {
  declare module.exports: any;
}

declare module 'react-detect-offline/src/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-detect-offline/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-detect-offline/coverage/lcov-report/prettify'>;
}
declare module 'react-detect-offline/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-detect-offline/coverage/lcov-report/sorter'>;
}
declare module 'react-detect-offline/dist/index.js' {
  declare module.exports: $Exports<'react-detect-offline/dist/index'>;
}
declare module 'react-detect-offline/src/index.js' {
  declare module.exports: $Exports<'react-detect-offline/src/index'>;
}
declare module 'react-detect-offline/src/index.spec.js' {
  declare module.exports: $Exports<'react-detect-offline/src/index.spec'>;
}
