// flow-typed signature: c119bd75b63eab1464eb45cf94e2e6b9
// flow-typed version: <<STUB>>/react-app-rewire-antd-theme_v^1.1.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-antd-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-antd-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-app-rewire-antd-theme/index' {
  declare module.exports: $Exports<'react-app-rewire-antd-theme'>;
}
declare module 'react-app-rewire-antd-theme/index.js' {
  declare module.exports: $Exports<'react-app-rewire-antd-theme'>;
}
