// flow-typed signature: d57e39df259ae608f265f095e126f5c6
// flow-typed version: <<STUB>>/remotedev_v^0.2.7/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remotedev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remotedev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remotedev/dist/remotedev' {
  declare module.exports: any;
}

declare module 'remotedev/dist/remotedev.min' {
  declare module.exports: any;
}

declare module 'remotedev/lib/constants' {
  declare module.exports: any;
}

declare module 'remotedev/lib/devTools' {
  declare module.exports: any;
}

declare module 'remotedev/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remotedev/dist/remotedev.js' {
  declare module.exports: $Exports<'remotedev/dist/remotedev'>;
}
declare module 'remotedev/dist/remotedev.min.js' {
  declare module.exports: $Exports<'remotedev/dist/remotedev.min'>;
}
declare module 'remotedev/lib/constants.js' {
  declare module.exports: $Exports<'remotedev/lib/constants'>;
}
declare module 'remotedev/lib/devTools.js' {
  declare module.exports: $Exports<'remotedev/lib/devTools'>;
}
declare module 'remotedev/lib/index.js' {
  declare module.exports: $Exports<'remotedev/lib/index'>;
}
