export const job = {
  id: 1,
  companyName: 'Guidewire Inc.',
  position: 'Software Engineer',
  startDate: '07/2017',
  endDate: null,
  isCurrentJob: true,
  city: 'Birmingham',
  state: 'AL',
  description: `*[Company 1][] description, particularly if not well-known.*
  
  **Position Title (include alternate titles in parentheses)** (Start Date - End Date)
  
  Lorem ipsum dolor sit amet consectetur adipiscing elit ad urna litora, nascetur integer tellus eu cursus vulputate neque nisl rhoncus, tristique risus donec hac arcu pretium enim platea non. Cursus elementum aptent ultrices dapibus dignissim justo imperdiet nibh ut, parturient curabitur pharetra libero nunc neque sed netus, arcu suscipit potenti ad at interdum quisque suspendisse.
  
  - Accomplishment that contains **bold text**.
  - Accomplishment
  - Accomplishment
  - Accomplishment
  `,
};

export const project = {
  id: 1,
  name: 'react-components',
  source: 'github',
  createdOn: 'Feb 2016',
  description: `Licuit Cycnus titulum cortice. Ales gravis illo, tenebras, rupisset
  [in](http://tamen-quarum.io/) lucemque, Phinea? Cytherea novitate, capiat
  umeroque at maius *hora quoque urbe* thalamoque, commonuit iuvenci e porto.
  Alcmenae et saepe.`,
  mainLanguage: 'javascript',
  numOfCommits: 212,
  numOfContributors: 7,
  numOfStars: 14,
};

export const user = {
  id: 1,
  token: 'some-secret-token',
  firstName: 'John',
  lastName: 'Davidson',
  email: 'jon@davidson.com',
  title: 'Software Engineer',
  website: 'https://davidson.com',
  keywords: ['javascript', 'aws', 'node', 'react', 'vue', 'go', 'mysql', 'postgres', 'ubuntu'],
  twitterUrl: 'https://twitter.com/deez',
  linkedInUrl: 'https://linkedin.com/deez',
  jobs: [job],
  projects: [project],
};

export const languages = [
  'APL',
  'AutoIt',
  'BASIC',
  'Eiffel',
  'Forth',
  'Frink',
  'Game Maker Language',
  'ICI',
  'J',
  'Lisp',
  'Lua',
  'M',
  'Pascal',
  'PCASTL',
  'Perl',
  'PostScript',
  'Python',
  'REXX',
  'Ruby',
  'S-Lang',
  'Spin',
  'Charity',
  'Clean',
  'Curry',
  'Erlang',
  'F#',
  'Haskell',
  'Joy',
  'Kite',
  'ML',
  'Nemerle',
  'OPAL',
  'OPS5',
  'Q',
  'Ada',
  'ALGOL',
  'C',
  'C++',
  'C#',
  'CLEO',
  'COBOL',
  'Cobra',
  'D',
  'DASL',
  'DIBOL',
  'Fortran',
  'Java',
  'JOVIAL',
  'Objective-C',
  'SMALL',
  'Smalltalk',
  'Turing',
  'Visual Basic',
  'Visual FoxPro',
  'XL',
  'Bliss',
  'ChucK',
  'CLIST',
  'HyperTalk',
  'Modula-2',
  'Oberon',
  'Component Pascal',
  'MATLAB',
  'Occam',
  'PL/C',
  'PL/I',
  'Rapira',
  'RPG',
  'AppleScript',
  'Awk',
  'BeanShell',
  'ColdFusion',
  'F-Script',
  'JASS',
  'Maya Embedded Language',
  'Mondrian',
  'PHP',
  'Revolution',
  'Tcl',
  'VBScript',
  'Windows PowerShell',
  'Curl',
  'SGML',
  'HTML',
  'XML',
  'XHTML',
  'ALF',
  'Fril',
  'Janus',
  'Leda',
  'Oz',
  'Poplog',
  'Prolog',
  'ROOP',
  'ABCL',
  'Afnix',
  'Cilk',
  'Concurrent Pascal',
  'E',
  'Joule',
  'Limbo',
  'Pict',
  'SALSA',
  'SR',
  'Agora',
  'BETA',
  'Cecil',
  'Lava',
  'Lisaac',
  'MOO',
  'Moto',
  'Object-Z',
  'Obliq',
  'Oxygene',
  'Pliant',
  'Prograph',
  'REBOL',
  'Scala',
  'Self',
  'Slate',
  'XOTcl',
  'IO',
  'Go',
];
